### ISSUE TITLE
No se aplicó correctamente la metodología

### ISSUE THREAD

**Issue by evolentini** [facasas17/TSE_TDD_LEDs#2]
Las pruebas deben primero fallar y despues de hacer los cambios recién deben pasar. Si una prueba pasa de primera instancia, entonces no prueba nada como en este caso donde los leds ya estan apagados antes de llamar a la función para apagarlos.

https://github.com/facasas17/TSE_TDD_LEDs/blob/b3ca572771a416628cc0d7cc34e639255a84784c/test/test_leds.c#L62-L65

**Comment by facasas17** [comment]
Agrego la función All_Leds_On() para encender todos los Leds y después llamo a la función All_Leds_Off()
