### ISSUE TITLE
Debería desdoblarse en dos pruebas

### ISSUE THREAD

**Issue by evolentini** [facasas17/TSE_TDD_LEDs#4]
Una que verifique el estado de un les apagado y otra que verifique el estado de un led encendido.

https://github.com/facasas17/TSE_TDD_LEDs/blob/b3ca572771a416628cc0d7cc34e639255a84784c/test/test_leds.c#L73-L80

**Comment by facasas17** [comment]
Perfecto! De hecho lo hice pero cambiaba a mano en TEST_ASSERT_EQUAL_HEX16(); entre 0 y 1 para comprobar que funcionaba para los dos estados. Ahora agrego la otra prueba
